In [1]:
# import necessary libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
# check for gpu availability
!nvidia-smi

Sun Aug 24 16:26:03 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   64C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Tensors

### Creating Tensors

In [3]:
# create a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# a scalar has no dimension, so this will return 0
scalar.ndim

0

In [5]:
# get the integer value of a scalar tensor
scalar.item()

7

In [6]:
# create a vector tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# check the number of dimensions of a vector
vector.ndim

1

In [8]:
# check the shape of a vector
vector.shape

torch.Size([2])

In [9]:
# create a matrix tensor
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# check the number of dimensions of a matrix
MATRIX.ndim

2

In [11]:
# check the shape of a matrix
MATRIX.shape

torch.Size([2, 2])

In [12]:
# access an element in a matrix
MATRIX[1]

tensor([ 9, 10])

In [13]:
# create a 3d tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# check the number of dimensions of a 3d tensor
TENSOR.ndim

3

In [15]:
# check the shape of a 3d tensor
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

**Why?** Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start w/ random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9349, 0.8544, 0.8478, 0.9847],
        [0.4692, 0.1938, 0.2252, 0.0486],
        [0.3503, 0.1373, 0.2499, 0.5628]])

In [17]:
# check the number of dimensions of the random tensor
random_tensor.ndim

2

In [18]:
# create a random tensor with a shape similar to an image (height, width, color channels)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [19]:
# create a tensor of all zeros with a given size
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# element-wise multiplication of two tensors
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones with a given size
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# check the data type of a tensor
ones.dtype

torch.float32

## Creating a range of tensor and tensors-like

In [23]:
# create a tensor with a range of values, `torch.range()` is deprecated, use `torch.arange()` instead
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [24]:
# create a tensor of zeros with the same shape as another tensor
torch.zeros_like(input=torch.arange(0, 10))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

**Note**: Three main errors you'll run into with PyTorch & Deep Learning
1. Tensors not right shape
2. Tensors not right data type
3. Tnesors not on the right device

In [25]:
# the default datatype in tensor is float32 even thought we might not explicitly mention it it
check_dataype = torch.tensor([3.0, 6.0, 9.0],
             dtype=None)

check_dataype.dtype

torch.float32

In [26]:
check_dataype2 = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what dataype is the tensor (e.g. float32 or float16)
                              device=None, # by default it'd be "cpu"; for gpu use "cuda"; basically this represents what device is your tensor on
                              requires_grad=False) # whether or not to track gradiants w/ this tensors operatins

check_dataype2.dtype

torch.float32

In [27]:
# change the datatype
changed_datatype = check_dataype2.type(torch.float16)
changed_datatype.dtype

torch.float16

# Getting information from tensor
1. Tensor not right datatype – use `tensor.dtype` to figure out the issue
2. Tensor not right shape - use `tensor.shape` to figure out the issue
3. Tensor not on the right device - use `tensor.device` to figure out the issue

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2614, 0.4045, 0.0938, 0.9629],
        [0.2173, 0.6948, 0.6537, 0.2778],
        [0.8243, 0.1923, 0.4182, 0.8313]])

In [29]:
# find out details about the above random tensor
print(random_tensor)
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is on: {random_tensor.device}")

tensor([[0.2614, 0.4045, 0.0938, 0.9629],
        [0.2173, 0.6948, 0.6537, 0.2778],
        [0.8243, 0.1923, 0.4182, 0.8313]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


# Manipulating Tensors (Tensor operations)

Operations include:
- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [30]:
# create a tensor and add, multiply, subtract, and divide 10
new_tensor = torch.tensor([1, 2, 3])
new_tensor + 10, new_tensor * 10, new_tensor - 1, new_tensor / 10

(tensor([11, 12, 13]),
 tensor([10, 20, 30]),
 tensor([0, 1, 2]),
 tensor([0.1000, 0.2000, 0.3000]))

In [31]:
# try out PyTorch in-built functions
torch.mul(new_tensor, 10), torch.add(new_tensor, 10), torch.sub(new_tensor, 1), torch.div(new_tensor, 10)

(tensor([10, 20, 30]),
 tensor([11, 12, 13]),
 tensor([0, 1, 2]),
 tensor([0.1000, 0.2000, 0.3000]))

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices – https://www.mathsisfun.com/algebra/matrix-multiplying.html

These are the two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimentions** must match:
- `(3, 2)` @ `(3, 2)` => won't work
- `(2, 3)` @ `(3, 2)` => will work
- `(3, 2)` @ `(2, 3)` => will work
2. The resulting matrix has the shape of the **outer dimensions**:
- `(2, 3)` @ `(3, 2)` => `(2, 2)`
- `(3, 2)` @ `(2, 3)` => `(3, 3)`

In [32]:
# element-wise multiplication
print(new_tensor, "*", new_tensor)
print(f"Equals: {new_tensor * new_tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [33]:
# matrix multiplication
matmul_tensor = torch.matmul(new_tensor, new_tensor) # 1*1+2*2+3*3={1+4+9}
matmul_tensor

tensor(14)

In [34]:
# verifying the time difference comparing the in-built function vs. multiplication by hand
%%time
value=0
for i in range(len(new_tensor)):
  value += new_tensor[i] * new_tensor[i]
print(value)

tensor(14)
CPU times: user 1.28 ms, sys: 0 ns, total: 1.28 ms
Wall time: 1.38 ms


In [35]:
%%time
torch.matmul(new_tensor, new_tensor)

CPU times: user 174 µs, sys: 0 ns, total: 174 µs
Wall time: 283 µs


tensor(14)

## One of the most common errors in deep learning: **shape errors**

In [36]:
## shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm() is the same as torch.matmul() => it's an alias for writing less code

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues we can manipulate the shape of one of our tensors using a **transpose**. A  **transpose** switches the axes or dimenstions of a given tensor.

In [38]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [39]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [40]:
torch.matmul(tensor_A, tensor_B.T), torch.matmul(tensor_A, tensor_B.T).shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

## Finding the mix, max, mean, sum, etc. (tensor aggregation)

In [41]:
# create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [42]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [43]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [44]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()  # note: the `torch.mean() function requires a tensor of float32 datatype to work

(tensor(45.), tensor(45.))

In [45]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))