In [1]:
# import necessary libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
# check for gpu availability
!nvidia-smi

Mon Jul 28 00:00:49 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Tensors

### Creating Tensors

In [3]:
# create a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# a scalar has no dimension, so this will return 0
scalar.ndim

0

In [5]:
# get the integer value of a scalar tensor
scalar.item()

7

In [6]:
# create a vector tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# check the number of dimensions of a vector
vector.ndim

1

In [8]:
# check the shape of a vector
vector.shape

torch.Size([2])

In [9]:
# create a matrix tensor
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# check the number of dimensions of a matrix
MATRIX.ndim

2

In [11]:
# check the shape of a matrix
MATRIX.shape

torch.Size([2, 2])

In [12]:
# access an element in a matrix
MATRIX[1]

tensor([ 9, 10])

In [13]:
# create a 3d tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# check the number of dimensions of a 3d tensor
TENSOR.ndim

3

In [15]:
# check the shape of a 3d tensor
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

**Why?** Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start w/ random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7826, 0.7402, 0.5812, 0.1459],
        [0.2607, 0.8651, 0.4443, 0.0180],
        [0.2247, 0.3448, 0.5447, 0.7741]])

In [17]:
# check the number of dimensions of the random tensor
random_tensor.ndim

2

In [18]:
# create a random tensor with a shape similar to an image (height, width, color channels)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [19]:
# create a tensor of all zeros with a given size
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# element-wise multiplication of two tensors
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones with a given size
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# check the data type of a tensor
ones.dtype

torch.float32

## Creating a range of tensor and tensors-like

In [23]:
# create a tensor with a range of values, `torch.range()` is deprecated, use `torch.arange()` instead
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [24]:
# create a tensor of zeros with the same shape as another tensor
torch.zeros_like(input=torch.arange(0, 10))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

**Note**: Three main errors you'll run into with PyTorch & Deep Learning
1. Tensors not right shape
2. Tensors not right data type
3. Tnesors not on the right device

In [25]:
# the default datatype in tensor is float32 even thought we might not explicitly mention it it
check_dataype = torch.tensor([3.0, 6.0, 9.0],
             dtype=None)

check_dataype.dtype

torch.float32

In [26]:
check_dataype2 = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # what dataype is the tensor (e.g. float32 or float16)
                              device=None, # by default it'd be "cpu"; for gpu use "cuda"; basically this represents what device is your tensor on
                              requires_grad=False) # whether or not to track gradiants w/ this tensors operatins

check_dataype2.dtype

torch.float32

In [27]:
# change the datatype
changed_datatype = check_dataype2.type(torch.float16)
changed_datatype.dtype

torch.float16

# Getting information from tensor
1. Tensor not right datatype – use `tensor.dtype` to figure out the issue
2. Tensor not right shape - use `tensor.shape` to figure out the issue
3. Tensor not on the right device - use `tensor.device` to figure out the issue

In [28]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7570, 0.7285, 0.6466, 0.1423],
        [0.8755, 0.9197, 0.0874, 0.1578],
        [0.8566, 0.5194, 0.0148, 0.4338]])

In [29]:
# find out details about the above random tensor
print(random_tensor)
print(f"Datatype of tensor: {random_tensor.dtype}")
print(f"Shape of tensor: {random_tensor.shape}")
print(f"Device tensor is on: {random_tensor.device}")

tensor([[0.7570, 0.7285, 0.6466, 0.1423],
        [0.8755, 0.9197, 0.0874, 0.1578],
        [0.8566, 0.5194, 0.0148, 0.4338]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
