<a href="https://colab.research.google.com/github/bxrdy/pytorch-notes/blob/main/fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import necessary libraries
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
# check for gpu availability
!nvidia-smi

Sun Jul 27 05:11:08 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

## Tensors

### Creating Tensors

In [3]:
# create a scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# a scalar has no dimension, so this will return 0
scalar.ndim

0

In [5]:
# get the integer value of a scalar tensor
scalar.item()

7

In [6]:
# create a vector tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# check the number of dimensions of a vector
vector.ndim

1

In [8]:
# check the shape of a vector
vector.shape

torch.Size([2])

In [9]:
# create a matrix tensor
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# check the number of dimensions of a matrix
MATRIX.ndim

2

In [11]:
# check the shape of a matrix
MATRIX.shape

torch.Size([2, 2])

In [12]:
# access an element in a matrix
MATRIX[1]

tensor([ 9, 10])

In [13]:
# create a 3d tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# check the number of dimensions of a 3d tensor
TENSOR.ndim

3

In [15]:
# check the shape of a 3d tensor
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

**Why?** Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`start w/ random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6646, 0.5578, 0.5235, 0.9804],
        [0.9024, 0.4404, 0.3883, 0.5303],
        [0.3446, 0.7270, 0.0048, 0.9306]])

In [17]:
# check the number of dimensions of the random tensor
random_tensor.ndim

2

In [18]:
# create a random tensor with a shape similar to an image (height, width, color channels)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros & Ones

In [19]:
# create a tensor of all zeros with a given size
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# element-wise multiplication of two tensors
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones with a given size
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
# check the data type of a tensor
ones.dtype

torch.float32

## Creating a range of tensor and tensors-like

In [23]:
# create a tensor with a range of values, `torch.range()` is deprecated, use `torch.arange()` instead
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [24]:
# create a tensor of zeros with the same shape as another tensor
torch.zeros_like(input=torch.arange(0, 10))

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])